import { describe, expect, it } from 'vitest';
import { normalizeRawMessage } from './normalize';

/** Helper to build a role:'agent' output record wrapping a user message (CLI transcript path). */
function agentOutputUser(uuid: string, content: string): any {
  return {
    role: 'agent',
    content: {
      type: 'output',
      data: {
        type: 'user',
        uuid,
        parentUuid: null,
        isSidechain: false,
        message: { role: 'user', content },
      },
    },
    meta: { source: 'cli' },
  };
}

/** Helper to build a role:'user' record (direct user message path). */
function directUser(text: string): any {
  return { role: 'user', content: { type: 'text', text } };
}

describe('typesRaw.normalizeRawMessage (local-command)', () => {
  // --- agent-output (CLI transcript) path ---

  it('drops <local-command-stdout> via agent-output path', () => {
    const raw = agentOutputUser('u1', '<local-command-stdout>Set model to claude-opus-4-6[1m]</local-command-stdout>');
    expect(normalizeRawMessage('m1', null, 1000, raw, { seq: 1 })).toBeNull();
  });

  it('drops <local-command-caveat> via agent-output path', () => {
    const raw = agentOutputUser('u2', '<local-command-caveat>Caveat: messages below were generated by local commands.</local-command-caveat>');
    expect(normalizeRawMessage('m2', null, 1001, raw, { seq: 2 })).toBeNull();
  });

  it('drops <command-name> via agent-output path', () => {
    const raw = agentOutputUser('u3', '<command-name>/model</command-name>');
    expect(normalizeRawMessage('m3', null, 1002, raw, { seq: 3 })).toBeNull();
  });

  it('drops "Unknown skill:" via agent-output path', () => {
    const raw = agentOutputUser('u4', 'Unknown skill: commit');
    expect(normalizeRawMessage('m4', null, 1003, raw, { seq: 4 })).toBeNull();
  });

  it('keeps regular user text via agent-output path', () => {
    const raw = agentOutputUser('u5', 'hello');
    const norm = normalizeRawMessage('m5', null, 1004, raw, { seq: 5 });
    expect(norm).not.toBeNull();
    expect((norm as any)?.role).toBe('user');
  });

  // --- direct role:'user' path ---

  it('drops <local-command-stdout> via direct user path', () => {
    expect(normalizeRawMessage('m6', null, 2000, directUser('<local-command-stdout>Set model</local-command-stdout>'), { seq: 6 })).toBeNull();
  });

  it('drops <local-command-caveat> via direct user path', () => {
    expect(normalizeRawMessage('m7', null, 2001, directUser('<local-command-caveat>Caveat</local-command-caveat>'), { seq: 7 })).toBeNull();
  });

  it('drops <command-name> via direct user path', () => {
    expect(normalizeRawMessage('m8', null, 2002, directUser('<command-name>/commit</command-name>'), { seq: 8 })).toBeNull();
  });

  it('drops <command-args> via direct user path', () => {
    expect(normalizeRawMessage('m9', null, 2003, directUser('<command-args>default</command-args>'), { seq: 9 })).toBeNull();
  });

  it('drops "Unknown skill:" via direct user path', () => {
    expect(normalizeRawMessage('m10', null, 2004, directUser('Unknown skill: commit'), { seq: 10 })).toBeNull();
  });

  it('keeps regular user text via direct user path', () => {
    const norm = normalizeRawMessage('m11', null, 2005, directUser('hello world'), { seq: 11 });
    expect(norm).not.toBeNull();
    expect((norm as any)?.role).toBe('user');
  });
});
